### ISSUE TITLE
The publish-nuget workflow doesn't fail when a package build has an error. (OSOE-566)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/GitHub-Actions#207]
Here is an example: https://github.com/Lombiq/Orchard-Vue.js/actions/runs/4146253609

I believe the error was thrown by the `dotnet pack`, but it's not sure from the log. In the end out of the 3 projects in Lombiq.VueJs only two were uploaded to NuGet. Since the workflow didn't fail, I didn't get a warning email so I could only find out about the problem when I dug into the run logs.

(I have already fixed that specific problem with Lombiq.VueJs, so this issue is not a blocker.)

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-566)

**Comment by Piedone** [comment]
Here's the error in the build log: https://github.com/Lombiq/Orchard-Vue.js/actions/runs/4146253609/jobs/7171672368#step:4:2620

![image](https://user-images.githubusercontent.com/1976647/226924616-51efac58-60b3-4b02-8692-57021e6fbe0c.png)

I suspect that in `New-NuGetPackage` we need to have a similar check on the output of `dotnet pack` that [what we have for the build](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/build-dotnet/Build-DotNetSolutionOrProject.ps1#L76).

**Comment by Piedone** [comment]
I couldn't reproduce this in NPM Targets, with the same error: https://github.com/Lombiq/NPM-Targets/actions/runs/4567948341/jobs/8062380293#step:4:338 For some reason, perhaps due to there being multiple projects, Vue.js runs to completion indeed: https://github.com/Lombiq/Orchard-Vue.js/actions/runs/4567982143/jobs/8062463289#step:4:2710 After the fix it fails as it should: https://github.com/Lombiq/Orchard-Vue.js/actions/runs/4567982143/jobs/8062577484#step:4:2685

BTW ChatGPT thought about the same solution after "Make the following script fail if dotnet pack fails:"

![image](https://user-images.githubusercontent.com/1976647/228930756-f10dcf41-358b-4c1a-8399-e2a3d541773c.png)
