### ISSUE TITLE
Test alternative runners and compare with BuildJet (OSOE-790)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/GitHub-Actions#318]
[BuildJet](https://buildjet.com/for-github-actions/docs/about/pricing) costs half of GitHub-hosted runners and [Ubicloud](https://www.ubicloud.com/use-cases/github-actions)-hosted runners cost 5th of BuildJet.

FYIs:
- They run on Hetzner.
- No 32-core runners at this point (although we don't need them).
- There are 1,250 free minutes per month, although it's unclear if it's vCore minutes or full machine minutes.

BuildJet is still quite cheap, so consider queue (runner start-up) time as highly important.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-790)

**Comment by Piedone** [comment]
Things to consider:

- We also use [BuildJet cache](https://buildjet.com/for-github-actions/docs/guides/migrating-to-buildjet-cache), which makes builds a lot faster. Ubicloud would need to offer better performance without it for the same or smaller cost.
- GDPR compliance and security. https://www.ubicloud.com/docs/github-actions-integration/security looks nice, but I can't find what the actual company is, if there's one, and where it is registered, which is important for GDPR. The team seems Turkish.
- Windows availability. Our Linux build costs are very little after all the optimization now, with Windows being the majority of our costs.

I've written them about the company and Windows.

**Comment by Piedone** [comment]
Windows won't come, GDPR compliance and info about the company behind it on the website will.

**Comment by Piedone** [comment]
There's also [WarpBuild](https://www.warpbuild.com/), which, amusingly, is the _third_ startup doing this from Y Combinator. Crowded space. That looks like it has [the exact same prices](https://www.warpbuild.com/pricing) as BuildJet.

Then [Namespace](https://namespace.so/) takes a different route with offering [mostly fixed plans](https://namespace.so/pricing) with minute-caps. [Cirrus Runners](https://cirrus-runners.app/) does something similar with $150/month/concurrent runner.

No Windows under either one, but it's ["coming soon" to WarpBuild](https://docs.warpbuild.com/#coming-soon).

**Comment by BenedekFarkas** [comment]
It's like Vultr vs. Digital Ocean. :D

**Comment by ozgune** [comment]
Hi @Piedone, @BenedekFarkas - thank you for looking into Ubicloud!

I'm Ozgun, one of Ubicloud's founders. @Piedone and I exchanged emails about Ubicloud runners (hi Zoltan!); and I also wanted to share that information here. Also happy to answer any other questions you might have.

Ubicloud is a Dutch-American company. Ubicloud BV is based in Amsterdam and serves our customers in Europe. Ubicloud Inc. is based in San Francisco and serves our customers in the US.

Umur, Daniel, and I are the company's co-founders. Umur and I previously co-founded Citus Data, where we built distributed PostgreSQL. We were acquired by Microsoft in 2019; and we led product and engineering teams within Azure. Daniel was instrumental in building Heroku Postgres and that's how we met him. The Ubicloud engineering team also previously worked at Citus / Microsoft.

We're big believers in open-source. At Citus, we [donated 1% of our stock](https://www.citusdata.com/blog/2018/10/24/why-citus-data-is-donating-1-percent-equity/) to non-profit PostgreSQL organizations. At Ubicloud, our project and GitHub integration is available here: https://github.com/ubicloud/ubicloud

We currently don't have Windows support. Once we introduce Windows VMs, I'd suspect we'd also provide GitHub runners for them. This however isn't on our roadmap for this quarter.

Caching support is on our roadmap. If you could share a bit more about your requirements, that would help us a lot. In particular, are you looking for a package cache similar to BuildJet's, a Docker instance registry, or a Docker layer cache?

Also, if this isn't a priority or you think Ubicloud isn't the right solution, completely understood. I came across this thread, just wanted to say hi, and see if there are any questions we could answer.

**Comment by Piedone** [comment]
Thanks for chiming in, Ozgun!

For caching, we need NuGet and NPM package caching. See from here down: https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/build-dotnet/action.yml#L97

Our biggest pain point is Windows costs, so that's what we'd look forward to most.

Secondly, more performance is always welcome. Our slowest Ubuntu workflow is something like what you see [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/workflows/build-and-test.yml?query=is%3Asuccess), which takes 13-20 minutes. Increasing core count from 4 brings marginal improvements, so 4 is the performance/cost sweet spot for this and similar workfows (at least on BuildJet). If we can have better performance for <=cost then awesome.

Note to ourselves: https://github.com/neysofu/awesome-github-actions-runners

**Comment by ozgune** [comment]
Hey @Piedone - sounds great! Will incorporate your feedback on the caching part.

BuildJet is great, runs on Hetzner like Ubicloud, and has amazing founders. For Ubicloud runners, we look to differentiate in the market with 10x lower cost than GitHub and open source.

**Comment by Piedone** [comment]
Thanks!

**Comment by suryaoruganti** [comment]
Hi @Piedone - I'm the founder of WarpBuild 👋

reg. caching: using the default github cache with WarpBuild speeds it up automagically by eliminating network bottlenecks.
We consistently have heard from customers that they prefer using us because they don't need to make any changes to caching, get unlimited concurrency out of the box with no additional charges, and also the best perf on most workloads.

I'd love for you to try us out.

**Comment by Piedone** [comment]
Thanks for the info, Surya, that sounds great! We'll need to do some comprehensive testing.
