### ISSUE TITLE
Fix NuGetBuild not taking effect in the publish-nuget action (OSOE-842)

### ISSUE THREAD

**Issue by DemeSzabolcs** [Lombiq/GitHub-Actions#342]
See: https://github.com/Lombiq/UI-Testing-Toolbox/actions/runs/8836448057/job/24264925167

It seems like [-p:NuGetBuild=true](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/publish-nuget/action.yml#L189) is not applied.

This is indicated here, because the action searches for `Lombiq.HelpfulLibraries.OrchardCore.csproj` instead of using the NuGet package: https://github.com/Lombiq/UI-Testing-Toolbox/actions/runs/8836448057/job/24264925167#step:4:207 and also here for `Lombiq.Npm.Targets.props`: https://github.com/Lombiq/UI-Testing-Toolbox/actions/runs/8836448057/job/24264925167#step:4:1304

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-842)

**Comment by Piedone** [comment]
This last worked on the 28th February [here](https://github.com/Lombiq/UI-Testing-Toolbox/actions/runs/8074837285). Possibly between .NET 8.0.201 and 8.0.204 this broke.

**Comment by Piedone** [comment]
Perhaps the .NET SDK change broke `-p` and we need to use `/p`.

**Comment by DemeSzabolcs** [comment]
> Perhaps the .NET SDK change broke `-p` and we need to use `/p`.

I already tried that on the parameters that are passed to NewNuGetPackage ps1 script or what it's called. Though I might missed something.

**Comment by Piedone** [comment]
BTW since we use `-p` everywhere, including for solution builds [here](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/build-dotnet/Build-DotNetSolutionOrProject.ps1), then if that were to be generally broken, all code analysis violations would be silent for all of ours builds too, and [that's not the case](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/8851305928/job/24307572593?pr=746). So, there's something else.

**Comment by Piedone** [comment]
And BTW [this HL publish](https://github.com/Lombiq/Helpful-Libraries/actions/runs/8623266546) also worked two weeks ago. So, NuGet publishing is not completely broken. However, that project doesn't use `NuGetBuild`.

**Comment by hyzx86** [comment]
Mark

https://github.com/EasyOC/EasyOC.Modules/actions/runs/8861373253/job/24333516410

```
Version number for the .NET build products: 1.8.0-preview-1
Building solution or project with `dotnet build  --configuration:Release --nologo --verbosity:minimal --warnaserror --warnAsMessage:MSB3026 --consoleLoggerParameters:NoSummary -p:TreatWarningsAsErrors=True -p:RunAnalyzersDuringBuild=false -p:Retries=4 -p:RetryDelayMilliseconds=1000 -p:Version=1.8.0-preview-1 --no-restore -p:NuGetBuild=true -p:LangVersion=Latest -p:GenerateDocumentationFile=True -p:NoWarn=CS1573%3BCS1591%3BVSTHRD002%3BVSTHRD200 -p:EnableNETAnalyzers=false -p:ContinuousIntegrationBuild=true -p:DebugSymbols=true -p:DebugType=portable`.

NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. 
```

**Comment by Piedone** [comment]
That's not this issue. You try to publish a .NET 8 project while the workflow sets up .NET 6.x. You'll need to pull the latest form this repo into EasyOC/GitHub-Actions, since the current version uses .NET 8, or configure .NET 8 with this option: https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/publish-nuget.yml#L28

BTW now we have versioning in this project, so you don't necessarily need to fork it, you can also reference `@v1.0` instead of the rolling release `@dev`.

**Comment by hyzx86** [comment]
> That's not this issue. You try to publish a .NET 8 project while the workflow sets up .NET 6.x. You'll need to pull the latest form this repo into EasyOC/GitHub-Actions, since the current version uses .NET 8, or configure .NET 8 with this option: https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/publish-nuget.yml#L28
> 
> BTW now we have versioning in this project, so you don't necessarily need to fork it, you can also reference `@v1.0` instead of the rolling release `@dev`.

Problem solved, thanks for guidance! 👍

**Comment by Piedone** [comment]
Awesome!

**Comment by Piedone** [comment]
Investigation notes:
- I have v8.0.204 of the .NET SDK, the same as on the runner, installed, but I'm on Windows.
- `dotnet build -p:NuGetBuild=true` works.
- Publishing BuildDisplayVersion works: https://github.com/Lombiq/Hosting-Build-Version-Display/actions/runs/8884033733/job/24392215283 It uses `NuGetBuild` to conditionally include `Lombiq.HelpfulLibraries.OrchardCore` and its build fails without it.
- In https://github.com/Lombiq/UI-Testing-Toolbox/actions/runs/8836448057/job/24264925167 what fails is something before the build. Most possibly `Add-SourceLinkPackage` due to it causing a restore but not passing the parameter.
- Debug failing publish for UITT: https://github.com/Lombiq/UI-Testing-Toolbox/actions/runs/8884157839/attempts/1
- `dotnet add Lombiq.Tests.UI/Lombiq.Tests.UI.csproj package 'Microsoft.SourceLink.GitHub' --source 'https://api.nuget.org/v3/index.json' --no-restore` fails locally too.
- Using `--no-restore` with `dotnet add package` doesn't help. But csproj inclusions work even without that.
- This was caused by https://github.com/Lombiq/GitHub-Actions/pull/341 Before that, https://github.com/Lombiq/GitHub-Actions/commit/d22e69d84e9afcdb214f7f11a21ea24f2a476fe3 added a new script that didn't bring over the workaround for this from the original .sh script.
- We need a manual file fix because `dotnet package add` can't skip these validations.

Fixed working publish: https://github.com/Lombiq/UI-Testing-Toolbox/actions/runs/8884157839/job/24394552735.
