### ISSUE TITLE
Add Git tags for Azure deployments and swaps (OSOE-861)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/GitHub-Actions#355]
We've talked about this in various ways, but here's an approach that I think is feasible and would be very useful to see what the state of the Azure app is in the repo.

- [ ] When doing a deployment, add a `staging/latest` (by default, configurable) tag to the current commit. This tag always points to the latest staging commit, so move it if it already exists. Also add a commit that contains the exact timestamp, e.g. `staging/2020-12-31-23:37UTC`, the same as the AI release annotation. This tag stays.
- [x] When doing a swap, look up the latest deployment tag and similarly add a `production/latest` (by default, configurable) tag to it (and always move to the latest) and a similar timestamp permanent tag. This will need a push token and repo URL configured, since the swap repo is different than the deploy repo.
- [x] Naming: To make it easier to browse (in GitExt for example) the naming structure could be e.g., `staging/latest` and `staging/{timestamp}` (because over time we'll have a lot of these). BTW same as with branches, you cannot have `staging` and `staging/latest` at the same time for example.
- [x] Swapping should also create a release in the code repo, this shouldn't be an issue based on the already present tags. Our central [`release-action`](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/actions/release-action/action.yml) would be extended as necessary; most possibly, just the `token`, `repo`, and `tag` options need to be proxied (see [the docs](https://github.com/ncipollo/release-action?tab=readme-ov-file#action-inputs)).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-861)

**Comment by Piedone** [comment]
@BenedekFarkas what do you think?

**Comment by Piedone** [comment]
And @wAsnk @DemeSzabolcs as PLs of two affected apps.

**Comment by wAsnk** [comment]
LGTM

**Comment by BenedekFarkas** [comment]
I think we talked about the problem of "I want to know what went into Production with the last swap" a couple months ago, so yeah, this is something I personally lack from our setup at the moment. The information is available, but a ready-made list would be convenient and useful.

Couple notes:
- Swap should also have a permanent (timestamped) tag and the timestamp should be the same as the datetime of the AI annotation, so they're easier to correlate (same goes for the timestamped tag for staging).
- Naming: To make it easier to browse (in GitExt for example) the naming structure could be e.g., `staging/latest` and `staging/{timestamp}` (because over time we'll have a lot of these). BTW same as with branches, you cannot have `staging` and `staging/latest` at the same time for example.
- Swapping should also create a release in the code repo, this shouldn't be an issue based on the already present tags.

**Comment by Piedone** [comment]
Added these to the description, thanks!

**Comment by Piedone** [comment]
@AydinE Tick above what you've completed.
