### ISSUE TITLE
Automatically check baseline package validation during review (OSOE-864)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/GitHub-Actions#359]
Right now it's too easy to accidentally introduce breaking changes, why not run the same check we do during `publish-nuget` also during the normal review flow? I suggest adding a label like `validate-baseline` which would run the check and write a comment on the PR if there are any results.

The same logic should be run by `done-jira-issue-if-checks-succeed` as well. This way the check would run once before the issues goes to review, giving useful info both the contributor and the reviewer.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-864)

**Comment by Piedone** [comment]
See from here on why we're not doing this now: https://github.com/Lombiq/GitHub-Actions/issues/220#issuecomment-1484859949

**Comment by sarahelsaig** [comment]
> [It would require constant maintenance of the suppression file.](https://github.com/Lombiq/GitHub-Actions/issues/45#issuecomment-1240568296)

If you intentionally introduce a breaking change, it's not much effort to document it in a suppression file. (way less effort than what we are already doing when we have to add a word to the global spell check dictionary for example) Seems like the hygienic thing to do. The only fiddly part is to remember to remove the suppressions after release.

**Comment by Piedone** [comment]
Fair enough.

We could introduce a dry run option to `publish-nuget`, that would run everything but the actual publish. This would default to being on when the trigger wasn't for a version tag, off otherwise. Then, in the consumer workflows [like this one](https://github.com/Lombiq/Helpful-Extensions/blob/dev/.github/workflows/publish-nuget.yml) we'd change the triggers to (in addition to the tag-based trigger) also include the same as build workflows, i.e. something like:

```
  pull_request:
  push:
    branches:
      - dev
```

This needs changes to all consumer workflows of ours though (the change is backward compatible if you don't want to utilize the new dry run).

Note that this is interesting only for submodules, not superprojects, so `done-jira-issue-if-checks-succeed` is not really applicable.
